# Generated by Django 2.1.3 on 2019-04-24 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freightman', '0002_auto_20190423_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirExportCreditNoteCosting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('is_unit_cost', models.BooleanField()),
                ('entry_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charge_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freightman.ChargeType')),
                ('credit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditnotecosting', related_query_name='creditnotecosting', to='freightman.AirExportConsolidatedShipmentCreditNote')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditnotecostingcurrency', to='freightman.Currency')),
                ('entry_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AirExportDebitNoteCosting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('is_unit_cost', models.BooleanField()),
                ('entry_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charge_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freightman.ChargeType')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debitnotecostingcurrency', to='freightman.Currency')),
                ('debit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debitnotecosting', related_query_name='debitnotecosting', to='freightman.AirExportConsolidatedShipmentDebitNote')),
                ('entry_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='airexportconsolidatedshipmentcreditnotetojobcostingmap',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='airexportconsolidatedshipmentcreditnotetojobcostingmap',
            name='credit_note',
        ),
        migrations.RemoveField(
            model_name='airexportconsolidatedshipmentcreditnotetojobcostingmap',
            name='job_costing',
        ),
        migrations.AlterUniqueTogether(
            name='airexportconsolidatedshipmentdebitnotetojobcostingmap',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='airexportconsolidatedshipmentdebitnotetojobcostingmap',
            name='debit_note',
        ),
        migrations.RemoveField(
            model_name='airexportconsolidatedshipmentdebitnotetojobcostingmap',
            name='job_costing',
        ),
        migrations.DeleteModel(
            name='AirExportConsolidatedShipmentCreditNoteToJobCostingMap',
        ),
        migrations.DeleteModel(
            name='AirExportConsolidatedShipmentDebitNoteToJobCostingMap',
        ),
    ]
