# Generated by Django 2.1.3 on 2019-04-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freightman', '0003_auto_20190424_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressbook',
            name='postcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
