# Generated by Django 2.1.3 on 2019-04-25 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freightman', '0004_auto_20190425_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hawb',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hawb_suplier', to='freightman.Organization'),
            preserve_default=False,
        ),
    ]
