# Generated by Django 2.1.3 on 2019-04-24 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seaexport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seaexporthbl',
            name='received_at_actual',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seaexporthbl',
            name='received_at_estimated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seaexporthbl',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seaexportgoodsreceivedby', to=settings.AUTH_USER_MODEL),
        ),
    ]
