# Generated by Django 2.1.3 on 2019-04-29 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freightman', '0005_auto_20190425_1225'),
        ('seaexport', '0008_auto_20190429_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='seaexportcontainerconsolshipment',
            name='supplier',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='seaexportcontainerconsolsupplier', to='freightman.Organization'),
            preserve_default=False,
        ),
    ]
