# Generated by Django 2.1.3 on 2019-05-02 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seaexport', '0009_seaexportcontainerconsolshipment_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seaexportcontainerconsolidationjobcosting',
            name='debit_or_credit',
        ),
        migrations.RemoveField(
            model_name='seaexportcontainerconsolidationjobcosting',
            name='unit_source',
        ),
    ]
