# Generated by Django 2.1.3 on 2019-04-23 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freightman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hawb',
            name='received_at_actual',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hawb',
            name='received_at_estimated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hawb',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='airexportgoodsreceivedby', to=settings.AUTH_USER_MODEL),
        ),
    ]
