# Generated by Django 2.1.3 on 2019-04-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freightman', '0005_auto_20190425_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressbook',
            name='contact',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='addressbook',
            name='state',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
