# Generated by Django 3.2 on 2022-06-17 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('freightman', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocatedOceanContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_serial', models.CharField(max_length=200)),
                ('container_number', models.CharField(max_length=200)),
                ('fcl_or_lcl', models.CharField(choices=[('fcl', 'fcl'), ('lcl', 'lcl')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='ContainerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('length_ft', models.FloatField()),
                ('width_ft', models.FloatField()),
                ('height_ft', models.FloatField()),
                ('capacity_cbm', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SeaExportContainerConsolShipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbl_number', models.CharField(max_length=50)),
                ('feeder_vessel_name', models.CharField(max_length=50)),
                ('feeder_vessel_voyage_number', models.CharField(max_length=50)),
                ('feeder_etd', models.DateField()),
                ('feeder_eta', models.DateField()),
                ('mother_vessel_name', models.CharField(max_length=50)),
                ('mother_vessel_voyage_number', models.CharField(max_length=50)),
                ('mother_etd', models.DateField()),
                ('mother_eta', models.DateField()),
                ('entry_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city_of_final_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seaexportcontainerconsolcityofdest', to='freightman.city')),
                ('city_of_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seaexportcontainerconsolcityofrcpt', to='freightman.city')),
                ('consignee_addressbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seaexportcontainerconsolconsigneeaddressbook', to='freightman.addressbook')),
                ('entry_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrybyseaexportcontainerconsol', related_query_name='entrybyseaexportcontainerconsol', to=settings.AUTH_USER_MODEL)),
                ('feeder_arrival_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeder_arrival_port', to='freightman.city')),
                ('feeder_departure_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeder_dept_port', to='freightman.city')),
                ('forwarder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seaexportcontainerconsolforwarder', to='freightman.organization')),
                ('mother_arrival_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mother_arrival_port', to='freightman.city')),
                ('mother_departure_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mother_dept_port', to='freightman.city')),
            ],
        ),
        migrations.CreateModel(
            name='SeaExportFreightBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_service', models.CharField(max_length=50)),
                ('delivery_note', models.TextField()),
                ('pickup_date', models.DateField()),
                ('pickup_time_start', models.CharField(max_length=10)),
                ('pickup_time_end', models.CharField(max_length=10)),
                ('pickup_note', models.TextField()),
                ('edd', models.DateField(blank=True, null=True)),
                ('entry_at', models.DateTimeField(auto_now_add=True)),
                ('is_draft', models.BooleanField(default=False)),
                ('is_booking_confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('goods_received', models.BooleanField(default=False)),
                ('goods_received_at', models.DateField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), related_name='confirmedbyseaexportbooking', related_query_name='confirmedbyseaexportbooking', to=settings.AUTH_USER_MODEL)),
                ('consignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seaexportbookingconsignee', related_query_name='seaexportbookingconsignee', to='freightman.addressbook')),
            ],
        ),
        migrations.CreateModel(
            name='SeaExportPackageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeaFrtChargeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeaTermsofDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('title', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeaTransportAgreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('details', models.TextField()),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seaexpttransportagreements', related_query_name='seaexpttransportagreements', to='freightman.organization')),
            ],
            options={
                'unique_together': {('org', 'title')},
            },
        ),
        migrations.CreateModel(
            name='SeaPort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seaportcity', to='freightman.city')),
            ],
        ),
        migrations.CreateModel(
            name='SeaExportMBL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbl_number', models.CharField(max_length=20, unique=True)),
                ('feeder_vessel_name', models.TextField()),
                ('voyage_number', models.TextField()),
                ('mother_vessel_name', models.TextField()),
                ('mother_vessel_voyage_number', models.TextField()),
                ('goods_no_of_packages', models.IntegerField()),
                ('goods_gross_weight_kg', models.FloatField()),
                ('goods_cbm', models.FloatField()),
                ('issue_date', models.DateField()),
                ('entry_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city_of_final_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seaexptmblcityofdest', related_query_name='seaexptmblcityofdest', to='freightman.city')),
                ('city_of_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seaexptmblcityofrcpt', related_query_name='seaexptmblcityofrcpt', to='freightman.city')),
                ('consignee_addressbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seaexportmblconsigneeaddressbook', to='freightman.addressbook')),
                ('entry_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrybyseaexportmbl', related_query_name='entrybyseaexportmbl', to=settings.AUTH_USER_MODEL)),
                ('forwarder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seaexportmblforwarder', related_query_name='seaexportmblforwarder', to='freightman.organization')),
                ('issue_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seaexptmblissuecity', related_query_name='seaexptmblissuecity', to='freightman.city')),
                ('port_of_discharge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seaexptmblportofdisc', related_query_name='seaexptmblportofdisc', to='seaexport.seaport')),
                ('port_of_loading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seaexptmblportofload', related_query_name='seaexptmblportofload', to='seaexport.seaport')),
                ('shipper_addressbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seaexportmblshipperaddressbook', to='freightman.addressbook')),
            ],
        ),
        migrations.CreateModel(
            name='SeaExportHBL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeder_vessel_name', models.TextField()),
                ('voyage_number', models.TextField()),
                ('mother_vessel_name', models.TextField()),
                ('mother_vessel_voyage_number', models.TextField()),
                ('excess_value_declaration', models.TextField()),
                ('goods_no_of_packages', models.IntegerField()),
                ('goods_gross_weight_kg', models.FloatField()),
                ('goods_cbm', models.FloatField()),
                ('no_of_pallet', models.IntegerField()),
                ('lot_number', models.IntegerField()),
                ('goods_note', models.TextField()),
                ('other_notes', models.TextField()),
                ('issue_date', models.DateField()),
                ('entry_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('received_at_estimated', models.DateTimeField(blank=True, null=True)),
                ('received_at_actual', models.DateTimeField(blank=True, null=True)),
                ('agent_addressbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seaexporthblagentaddressbook', related_query_name='seaexporthblagentaddressbook', to='freightman.addressbook')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seaexpthblbooking', related_query_name='seaexpthblbooking', to='seaexport.seaexportfreightbooking')),
                ('city_of_final_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seaexpthblcityofdest', related_query_name='seaexpthblcityofdest', to='freightman.city')),
                ('city_of_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seaexpthblcityofrcpt', related_query_name='seaexpthblcityofrcpt', to='freightman.city')),
                ('consignee_addressbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seaexporthblconsigneeaddressbook', to='freightman.addressbook')),
                ('entry_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrybyseaexporthbl', related_query_name='entrybyseaexporthbl', to=settings.AUTH_USER_MODEL)),
                ('forwarder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seaexporthblforwarder', related_query_name='seaexporthblforwarder', to='freightman.organization')),
                ('issue_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seaexpthblissuecity', related_query_name='seaexpthblissuecity', to='freightman.city')),
                ('port_of_discharge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seaexpthblportofdisc', related_query_name='seaexpthblportofdisc', to='seaexport.seaport')),
                ('port_of_loading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seaexpthblportofload', related_query_name='seaexpthblportofload', to='seaexport.seaport')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seaexportgoodsreceivedby', to=settings.AUTH_USER_MODEL)),
                ('shipper_addressbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seaexporthblshipperaddressbook', to='freightman.addressbook')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seaexpthblsupplier', related_query_name='seaexpthblsupplier', to='freightman.organization')),
            ],
        ),
        migrations.CreateModel(
            name='SeaExportFreightBookingStakeholderReferenceTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=50)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookingseaexportfreightbookingstakeholderreferencetypes', related_query_name='bookingseaexportfreightbookingstakeholderreferencetypes', to='seaexport.seaexportfreightbooking')),
                ('reference_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refsseaexportfreightbookingstakeholderreferencetypes', related_query_name='refsseaexportfreightbookingstakeholderreferencetypes', to='freightman.stakeholderreferencetypes')),
            ],
        ),
        migrations.CreateModel(
            name='SeaExportFreightBookingNotifyAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addressseaexportfreightbookingnotify', related_query_name='addressseaexportfreightbookingnotify', to='freightman.addressbook')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookingseaexportfreightbookingnotify', related_query_name='bookingseaexportfreightbookingnotify', to='seaexport.seaexportfreightbooking')),
            ],
        ),
        migrations.CreateModel(
            name='SeaExportFreightBookingMoreAddressMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_shipper', models.BooleanField(default=False)),
                ('is_consignee', models.BooleanField(default=False)),
                ('is_consignor', models.BooleanField(default=False)),
                ('is_pickup', models.BooleanField(default=False)),
                ('is_delivery', models.BooleanField(default=False)),
                ('addressbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addressseaexportfreightbookingmoreaddressmap', related_query_name='addressseaexportfreightbookingmoreaddressmap', to='freightman.addressbook')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookingseaexportfreightbookingmoreaddressmap', related_query_name='bookingseaexportfreightbookingmoreaddressmap', to='seaexport.seaexportfreightbooking')),
            ],
        ),
        migrations.CreateModel(
            name='SeaExportFreightBookingGoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_pieces', models.IntegerField()),
                ('weight_kg', models.FloatField()),
                ('cbm', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('unit_price', models.FloatField()),
                ('shipping_mark', models.TextField(default='')),
                ('goods_desc', models.TextField(default='')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seaexportfreightbookinggoodsinfo', related_query_name='seaexportfreightbookinggoodsinfo', to='seaexport.seaexportfreightbooking')),
                ('currency', models.ForeignKey(on_delete=models.SET(None), to='freightman.currency')),
                ('package_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seaexport.seaexportpackagetype')),
            ],
        ),
        migrations.CreateModel(
            name='SeaExportFreightBookingAttachedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=200, upload_to='media/')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seaexportfreightbookingattachedfile', to='seaexport.seaexportfreightbooking')),
            ],
        ),
        migrations.AddField(
            model_name='seaexportfreightbooking',
            name='delivery_terms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverytermsseaexportbooking', related_query_name='deliverytermsseaexportbooking', to='seaexport.seatermsofdelivery'),
        ),
        migrations.AddField(
            model_name='seaexportfreightbooking',
            name='destination_bank_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seaexportbookingdest', related_query_name='seaexportbookingdest', to='freightman.bankbranch'),
        ),
        migrations.AddField(
            model_name='seaexportfreightbooking',
            name='destination_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destcountryseaexportbooking', related_query_name='destcountryseaexportbooking', to='freightman.country'),
        ),
        migrations.AddField(
            model_name='seaexportfreightbooking',
            name='destination_port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seaexportbookingdest', related_query_name='seaexportbookingdest', to='seaexport.seaport'),
        ),
        migrations.AddField(
            model_name='seaexportfreightbooking',
            name='entry_by',
            field=models.ForeignKey(on_delete=models.SET(None), related_name='entrybyseaexportbooking', related_query_name='entrybyseaexportbooking', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seaexportfreightbooking',
            name='forwarder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seaexportbookingforwarder', related_query_name='seaexportbookingforwarder', to='freightman.organization'),
        ),
        migrations.AddField(
            model_name='seaexportfreightbooking',
            name='goods_received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seafrtbookgoodsreceivedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seaexportfreightbooking',
            name='loading_port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seaexportbookingloading', related_query_name='seaexportbookingloading', to='seaexport.seaport'),
        ),
        migrations.AddField(
            model_name='seaexportfreightbooking',
            name='origin_bank_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seaexportbookingorigin', related_query_name='seaexportbookingorigin', to='freightman.bankbranch'),
        ),
        migrations.AddField(
            model_name='seaexportfreightbooking',
            name='payment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymenttypeseaexportbooking', related_query_name='paymenttypeseaexportbooking', to='freightman.paymenttype'),
        ),
        migrations.AddField(
            model_name='seaexportfreightbooking',
            name='shipper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seaexportbookingshipper', related_query_name='seaexportbookingshipper', to='freightman.addressbook'),
        ),
        migrations.AddField(
            model_name='seaexportfreightbooking',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seaexportbookingsupplier', related_query_name='seaexportbookingsupplier', to='freightman.organization'),
        ),
        migrations.AddField(
            model_name='seaexportfreightbooking',
            name='transport_agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transportagreementseaexportbooking', related_query_name='transportagreementseaexportbooking', to='seaexport.seatransportagreement'),
        ),
        migrations.CreateModel(
            name='SeaExportDebitNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_who', models.CharField(choices=[('mbl_consignee', 'mbl_consignee'), ('hbl_supplier', 'hbl_supplier'), ('hbl_shipper', 'hbl_shipper')], max_length=50)),
                ('date', models.DateField()),
                ('entry_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('container_consol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seaexportdebitnoteconsol', to='seaexport.seaexportcontainerconsolshipment')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seaexptdebitnotedcurrency', to='freightman.currency')),
                ('entry_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('forwarder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seaexptconsshptdebitnoteforwarder', to='freightman.organization')),
                ('hbl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seaexport.seaexporthbl')),
                ('target_currency_conversion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seaexptdebitnotecurrencyconversion', to='freightman.currencyconversion')),
            ],
            options={
                'unique_together': {('container_consol', 'to_who')},
            },
        ),
        migrations.CreateModel(
            name='SeaExportContainerConsolShipmentToAllocatedContainerMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seaexptcontainerconsolallocatedcontainer', to='seaexport.allocatedoceancontainer')),
                ('container_consol_shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seaexptcontainerconsolshpmnt', to='seaexport.seaexportcontainerconsolshipment')),
            ],
            options={
                'unique_together': {('container_consol_shipment', 'allocated_container')},
            },
        ),
        migrations.AddField(
            model_name='seaexportcontainerconsolshipment',
            name='port_of_discharge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seaexportcontainerconsolportofdisc', to='seaexport.seaport'),
        ),
        migrations.AddField(
            model_name='seaexportcontainerconsolshipment',
            name='port_of_loading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seaexportcontainerconsolportofload', to='seaexport.seaport'),
        ),
        migrations.AddField(
            model_name='seaexportcontainerconsolshipment',
            name='shipper_addressbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seaexportcontainerconsolshipperaddressbook', to='freightman.addressbook'),
        ),
        migrations.AddField(
            model_name='seaexportcontainerconsolshipment',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seaexportcontainerconsolsupplier', to='freightman.organization'),
        ),
        migrations.CreateModel(
            name='SeaExportContainerConsolidationJobCosting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('perunit_or_fixed', models.CharField(choices=[('perunit', 'perunit'), ('fixed', 'fixed')], max_length=10)),
                ('entry_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charge_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seaexport.seafrtchargetype')),
                ('container_consol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seaexportconsoljobcosting', related_query_name='seaexportconsoljobcosting', to='seaexport.seaexportcontainerconsolshipment')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seaexportconsoljobcostingcurrency', to='freightman.currency')),
                ('currency_conversion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seaexportconsoljobcostingcurrencyconversion', to='freightman.currencyconversion')),
                ('entry_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('forwarder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seaexptconsoljobcostingforwarder', to='freightman.organization')),
                ('hbl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seaexptconjobcostngshptcosthbl', to='seaexport.seaexporthbl')),
            ],
        ),
        migrations.AddField(
            model_name='allocatedoceancontainer',
            name='container_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocatedoceancontainertype', related_query_name='allocatedoceancontainertype', to='seaexport.containertype'),
        ),
        migrations.CreateModel(
            name='SeaExportMBLToHBLMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_at', models.DateTimeField(auto_now_add=True)),
                ('entry_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seaexportmblhblmapperuser', to=settings.AUTH_USER_MODEL)),
                ('hbl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seaexportmblhblmaphbl', to='seaexport.seaexporthbl')),
                ('mbl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seaexportmblhblmapmbl', to='seaexport.seaexportmbl')),
            ],
            options={
                'unique_together': {('mbl', 'hbl')},
            },
        ),
        migrations.CreateModel(
            name='SeaExportHBLContainerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seaexporthblallocatedcontainer', related_query_name='seaexporthblallocatedcontainer', to='seaexport.allocatedoceancontainer')),
                ('hbl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seaexporthblcontainerinfo', related_query_name='seaexporthblcontainerinfo', to='seaexport.seaexporthbl')),
            ],
            options={
                'unique_together': {('hbl', 'allocated_container')},
            },
        ),
        migrations.CreateModel(
            name='SeaExportFreightBookingGoodsReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=50)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refsseaexportfreightbookinggoodsrefbooking', related_query_name='refsseaexportfreightbookinggoodsrefbooking', to='seaexport.seaexportfreightbooking')),
                ('goods_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refsseaexportfreightbookinggoodsref', to='seaexport.seaexportfreightbookinggoodsinfo')),
                ('reference_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refsseaexportfreightbookinggoodsreftype', related_query_name='refsseaexportfreightbookinggoodsreftype', to='freightman.stakeholderreferencetypes')),
            ],
            options={
                'unique_together': {('goods_info', 'reference_type', 'reference_number')},
            },
        ),
        migrations.CreateModel(
            name='SeaExportDebitNoteToJobCostingMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seaexport.seaexportdebitnote')),
                ('job_costing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seaexport.seaexportcontainerconsolidationjobcosting')),
            ],
            options={
                'unique_together': {('debit_note', 'job_costing')},
            },
        ),
        migrations.CreateModel(
            name='SeaExportContainerConsolShipmentAllocatedContainerToHBLMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hbl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seaexptcontainerconsolhbl', to='seaexport.seaexporthbl')),
                ('shipment_to_container_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seaexptconsolcontainermap', to='seaexport.seaexportcontainerconsolshipmenttoallocatedcontainermap')),
            ],
            options={
                'unique_together': {('shipment_to_container_map', 'hbl')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='allocatedoceancontainer',
            unique_together={('container_type', 'container_serial', 'container_number')},
        ),
    ]
