# Generated by Django 2.1.3 on 2019-04-28 12:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('seaexport', '0003_auto_20190425_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='seaexportcontainerconsolshipment',
            name='feeder_arrival_port_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='feeder_arrival_port', to='seaexport.SeaPort'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seaexportcontainerconsolshipment',
            name='feeder_departure_port',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='feeder_dept_port', to='seaexport.SeaPort'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seaexportcontainerconsolshipment',
            name='feeder_eta',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seaexportcontainerconsolshipment',
            name='feeder_etd',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seaexportcontainerconsolshipment',
            name='mother_arrival_port_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mother_arrival_port', to='seaexport.SeaPort'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seaexportcontainerconsolshipment',
            name='mother_departure_port_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mother_dept_port', to='seaexport.SeaPort'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seaexportcontainerconsolshipment',
            name='mother_eta',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seaexportcontainerconsolshipment',
            name='mother_etd',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seaexportcontainerconsolshipment',
            name='feeder_vessel_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='seaexportcontainerconsolshipment',
            name='mbl_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='seaexportcontainerconsolshipment',
            name='mother_vessel_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='seaexportcontainerconsolshipment',
            name='mother_vessel_voyage_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='seaexportcontainerconsolshipment',
            name='voyage_number',
            field=models.CharField(max_length=50),
        ),
    ]
