# Generated by Django 2.1.3 on 2019-04-29 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freightman', '0005_auto_20190425_1225'),
        ('seaexport', '0006_auto_20190428_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='seaexportcontainerconsolshipment',
            name='consignee_addressbook',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='seaexportcontainerconsolconsigneeaddressbook', to='freightman.AddressBook'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seaexportcontainerconsolshipment',
            name='shipper_addressbook',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='seaexportcontainerconsolshipperaddressbook', to='freightman.AddressBook'),
            preserve_default=False,
        ),
    ]
